# Generated by Django 6.0 on 2026-02-02 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
