# Generated by Django 6.0 on 2026-02-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_alter_thread_category_thread_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='category',
        ),
    ]
